create table alumno (id_alumno  serial not null, tx_nombre varchar(50) not null, tx_primer_ape varchar(50) not null, tx_segundo_ape varchar(50) not null, tx_curp varchar(18) not null unique, fh_nacimiento int4 not null, tx_boleta varchar(10) not null unique, primary key (id_alumno));
create table unidad_academica (id_unidad  serial not null, tx_nombre varchar(250), tx_acronimo varchar(20), primary key (id_unidad));
create table area_conocimiento (id_area  serial not null, tx_nombre int4, primary key (id_area));
create table programa_academico (id_programa  serial not null, id_area int4 not null, id_nivel int4 not null, tx_nombre varchar(250), primary key (id_programa));
create table nivel_academico (id_nivel  serial not null, tx_nombre int4, primary key (id_nivel));
create table unidad_academica_programa (id_unidad int4 not null, id_programa int4 not null, primary key (id_unidad, id_programa));
create table plan_estudio (id_plan  serial not null, id_programa int4 not null, tx_nombre varchar(100), primary key (id_plan));
create table nivel (id_nivel  serial not null, id_plan int4 not null, nu_nivel int4, primary key (id_nivel));
create table materia (id_materia  serial not null, id_nivel int4 not null, id_tipo int4 not null, tx_nombre varchar(250), nu_credito float4, primary key (id_materia));
create table tipo_materia (id_tipo  serial not null, tx_nombre varchar(100), primary key (id_tipo));
create table inscripcion (id_alumno int4 not null, id_unidad int4 not null, id_programa int4 not null, id_plan int4 not null, primary key (id_alumno, id_unidad, id_programa, id_plan));
create table reinscripcion (id_alumno int4 not null, id_unidad int4 not null, id_programa int4 not null, id_plan int4 not null, id_nivel int4 not null, id_periodo int4 not null, primary key (id_alumno, id_unidad, id_programa, id_plan, id_nivel, id_periodo));
create table ciclo_escolar (id_ciclo  serial not null, fh_inicio date, fh_fin date, primary key (id_ciclo));
create table periodo_escolar (id_periodo  serial not null, id_ciclo int4 not null, fh_inicio date, fh_fin date, primary key (id_periodo));
create table curse (id_curse  serial not null, id_alumno int4 not null, id_unidad int4 not null, id_programa int4 not null, id_plan int4 not null, id_nivel int4 not null, id_periodo int4 not null, id_materia int4 not null, primary key (id_curse));
create table calificacion_curse (id_calificacion_curse  serial not null, id_curse int4 not null, id_calificacion int4 not null, primary key (id_calificacion_curse));
create table calificacion (id_calificacion  serial not null, tx_nombre int4, nu_calificacion int4, primary key (id_calificacion));
alter table programa_academico add constraint FKprograma_a382072 foreign key (id_area) references area_conocimiento;
alter table programa_academico add constraint FKprograma_a947718 foreign key (id_nivel) references nivel_academico;
alter table unidad_academica_programa add constraint FKunidad_aca352322 foreign key (id_unidad) references unidad_academica;
alter table unidad_academica_programa add constraint FKunidad_aca139359 foreign key (id_programa) references programa_academico;
alter table plan_estudio add constraint FKplan_estud937865 foreign key (id_programa) references programa_academico;
alter table nivel add constraint FKnivel821866 foreign key (id_plan) references plan_estudio;
alter table materia add constraint FKmateria58989 foreign key (id_nivel) references nivel;
alter table materia add constraint FKmateria489379 foreign key (id_tipo) references tipo_materia;
alter table inscripcion add constraint FKinscripcio997981 foreign key (id_alumno) references alumno;
alter table inscripcion add constraint FKinscripcio266489 foreign key (id_unidad, id_programa) references unidad_academica_programa;
alter table inscripcion add constraint FKinscripcio510375 foreign key (id_plan) references plan_estudio;
alter table reinscripcion add constraint FKreinscripc247347 foreign key (id_alumno) references alumno;
alter table reinscripcion add constraint FKreinscripc847667 foreign key (id_nivel) references nivel;
alter table reinscripcion add constraint FKreinscripc17124 foreign key (id_unidad, id_programa) references unidad_academica_programa;
alter table reinscripcion add constraint FKreinscripc261010 foreign key (id_plan) references plan_estudio;
alter table periodo_escolar add constraint FKperiodo_es204303 foreign key (id_ciclo) references ciclo_escolar;
alter table reinscripcion add constraint FKreinscripc763901 foreign key (id_periodo) references periodo_escolar;
alter table curse add constraint FKcurse692357 foreign key (id_alumno, id_unidad, id_programa, id_plan, id_nivel, id_periodo) references reinscripcion;
alter table curse add constraint FKcurse467302 foreign key (id_materia) references materia;
alter table calificacion_curse add constraint FKcalificaci850406 foreign key (id_curse) references curse;
alter table calificacion_curse add constraint FKcalificaci719397 foreign key (id_calificacion) references calificacion;
